# Configuration reference:
# https://circleci.com/docs/ja/2.0/configuration-reference
version: 2.1
orbs:
  # Using CircleCI's official orb
  # https://circleci.com/orbs/registry/orb/circleci/node?version=1.1.6
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      # Auto caching
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
